In [18]:
### 1. Write a Python Program to Add Two Matrices?
import numpy as np
A =[[1,2],
    [3,4]]
B=[[5,6],
    [7,8]]
a=np.array(A)
b= np.array(B)
print('Sum of two matrice is', '\n', a+b)

Sum of two matrice is 
 [[ 6  8]
 [10 12]]


In [27]:
### 2. Write a Python Program to Multiply Two Matrices?
import numpy as np
A =[[1,2],[3,4]]
B=[[5,6],[7,8]]
a=np.array(A)
b= np.array(B)
print('Multiplication  of two matrice is', '\n', a*b)

Multiplication  of two matrice is 
 [[ 5 12]
 [21 32]]


In [31]:
### 3. Write a Python Program to Transpose a Matrix?
import numpy as np
A =[[1,2],[3,4]]
a=np.array(A)
print('Transpose of a matrix is ','\n' , np.transpose(a))

Transpose of a matrix is  
 [[1 3]
 [2 4]]


In [4]:
### 4. Write a Python Program to Sort Words in Alphabetic Order?
str=input('enter a string')
words = str.split()
words.sort()
print('sorting letters ' , words )

enter a string i am a very good human being


sorting letters  ['a', 'am', 'being', 'good', 'human', 'i', 'very']


In [ ]:
### 5. Write a Python Program to Remove Punctuation From a String?
punctuation = '''''! ()-[]{};:'"\,<>./? @#$%^&*_~'''
str= input('enter a string')
no_punct =""
for i in str:
    if i not in punctuation:
        no_punct = no_punct + i
print('Letter of string without punctuation is  ', no_punct)

In [8]:
str= input('enter a string')
for i in str:
    print(i)

enter a string i am puisjsd


i
 
a
m
 
p
u
i
s
j
s
d
